name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    - name: Checkout
          uses: actions/checkout@v2
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        path: |
          test/awesome-website.zip
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
      files: |
        awesome-website.zip